[package]
edition.workspace      = true
license.workspace      = true
name                   = "viperzoo-assets"
rust-version.workspace = true
version.workspace      = true

[dependencies]
thiserror.workspace = true
tracing.workspace   = true

[dependencies.viperzoo-protocol]
path    = "../protocol"
version = "0.1.0"

[lints]
workspace = true
