[formatting]
align_entries         = true
array_auto_expand     = true
array_auto_collapse   = false
array_trailing_comma  = true
compact_arrays        = false
compact_inline_tables = false
inline_table_expand   = true
trailing_newline      = true
