[package]
edition.workspace      = true
license.workspace      = true
name                   = "viperzoo-navigation"
rust-version.workspace = true
version.workspace      = true

[dependencies]
thiserror.workspace = true
tracing.workspace   = true

[dependencies.viperzoo-assets]
path    = "../assets"
version = "0.1.0"

[dependencies.viperzoo-protocol]
path    = "../protocol"
version = "0.1.0"

[dependencies.viperzoo-world]
path    = "../world"
version = "0.1.0"

[dev-dependencies]
hex.workspace = true

[lints]
workspace = true
