[package]
edition.workspace      = true
license.workspace      = true
name                   = "viperzoo-adapter-api"
rust-version.workspace = true
version.workspace      = true

[dependencies]
futures-core.workspace = true
thiserror.workspace    = true
viperzoo-protocol      = { version = "0.1.0", path = "../protocol" }

[dev-dependencies]
tokio = { workspace = true, features = [ "macros", "rt" ] }

[lints]
workspace = true
