[package]
edition.workspace      = true
license.workspace      = true
name                   = "viperzoo-live"
rust-version.workspace = true
version.workspace      = true

[dependencies]
bytes.workspace              = true
serde.workspace              = true
serde_json.workspace         = true
thiserror.workspace          = true
tokio-util.workspace         = true
tracing.workspace            = true
tracing-subscriber.workspace = true

[dependencies.tokio]
workspace = true
features = [
  "fs",
  "io-std",
  "io-util",
  "macros",
  "rt",
  "time",
]

[dependencies.viperzoo-adapter-api]
path    = "../../crates/adapter-api"
version = "0.1.0"

[dependencies.viperzoo-capture]
path    = "../../crates/capture"
version = "0.1.0"

[dependencies.viperzoo-engine]
path    = "../../crates/engine"
version = "0.1.0"

[dependencies.viperzoo-protocol]
path    = "../../crates/protocol"
version = "0.1.0"

[dependencies.viperzoo-world]
path    = "../../crates/world"
version = "0.1.0"

[lints]
workspace = true
