[package]
edition.workspace      = true
license.workspace      = true
name                   = "viperzoo-protocol"
rust-version.workspace = true
version.workspace      = true

[dependencies]
bytes.workspace      = true
encoding_rs          = "0.8"
hex.workspace        = true
serde.workspace      = true
thiserror.workspace  = true
tokio-util.workspace = true
tracing.workspace    = true

[lints]
workspace = true
