[package]
edition.workspace      = true
license.workspace      = true
name                   = "viperzoo-world"
rust-version.workspace = true
version.workspace      = true

[dependencies]
serde.workspace      = true
tracing.workspace    = true
viperzoo-adapter-api = { version = "0.1.0", path = "../adapter-api" }
viperzoo-protocol    = { version = "0.1.0", path = "../protocol" }

[dev-dependencies]
hex.workspace        = true
serde_json.workspace = true

[lints]
workspace = true
