[package]
edition.workspace      = true
license.workspace      = true
name                   = "viperzoo"
rust-version.workspace = true
version.workspace      = true

[dependencies]
thiserror.workspace = true
tokio = { workspace = true, features = [
  "macros",
  "rt",
  "signal",
  "sync",
  "time",
] }
tracing.workspace = true
tracing-subscriber.workspace = true
viperzoo-adapter-frida = { version = "0.1.0", path = "../../crates/adapter-frida" }
viperzoo-engine = { version = "0.1.0", path = "../../crates/engine" }
viperzoo-world = { version = "0.1.0", path = "../../crates/world" }

[lints]
workspace = true
