[package]
edition.workspace      = true
license.workspace      = true
name                   = "viperzoo-actions"
rust-version.workspace = true
version.workspace      = true

[dependencies]
thiserror.workspace = true
tracing.workspace   = true

[dependencies.tokio]
features  = [ "sync", "time" ]
workspace = true

[dependencies.viperzoo-adapter-api]
path    = "../adapter-api"
version = "0.1.0"

[dependencies.viperzoo-assets]
path    = "../assets"
version = "0.1.0"

[dependencies.viperzoo-engine]
path    = "../engine"
version = "0.1.0"

[dependencies.viperzoo-navigation]
path    = "../navigation"
version = "0.1.0"

[dependencies.viperzoo-protocol]
path    = "../protocol"
version = "0.1.0"

[dependencies.viperzoo-world]
path    = "../world"
version = "0.1.0"

[dev-dependencies]
hex.workspace = true

[dev-dependencies.tokio]
features  = [ "macros", "rt" ]
workspace = true

[dev-dependencies.viperzoo-adapter-api]
features = [ "test-util" ]
path     = "../adapter-api"
version  = "0.1.0"

[lints]
workspace = true
