[package]
edition.workspace      = true
license.workspace      = true
name                   = "viperzoo-replay"
rust-version.workspace = true
version.workspace      = true

[dependencies]
serde.workspace              = true
serde_json.workspace         = true
thiserror.workspace          = true
tokio-stream.workspace       = true
tokio-util.workspace         = true
tracing.workspace            = true
tracing-subscriber.workspace = true

[dependencies.tokio]
features  = [ "fs", "io-util", "macros", "rt" ]
workspace = true

[dependencies.viperzoo-adapter-api]
path    = "../../crates/adapter-api"
version = "0.1.0"

[dependencies.viperzoo-capture]
path    = "../../crates/capture"
version = "0.1.0"

[dependencies.viperzoo-engine]
path    = "../../crates/engine"
version = "0.1.0"

[dependencies.viperzoo-world]
path    = "../../crates/world"
version = "0.1.0"

[dev-dependencies]

[dev-dependencies.viperzoo-protocol]
path    = "../../crates/protocol"
version = "0.1.0"

[lints]
workspace = true
