[package]
edition.workspace      = true
license.workspace      = true
name                   = "viperzoo-replay"
rust-version.workspace = true
version.workspace      = true

[dependencies]
serde.workspace              = true
serde_json.workspace         = true
thiserror.workspace          = true
tracing.workspace            = true
tracing-subscriber.workspace = true
viperzoo-adapter-api         = { version = "0.1.0", path = "../../crates/adapter-api" }
viperzoo-capture             = { version = "0.1.0", path = "../../crates/capture" }
viperzoo-engine              = { version = "0.1.0", path = "../../crates/engine" }
viperzoo-world               = { version = "0.1.0", path = "../../crates/world" }

[dev-dependencies]
viperzoo-protocol = { version = "0.1.0", path = "../../crates/protocol" }

[lints]
workspace = true
